# Generated by Django 3.2.5 on 2021-08-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlist', '0003_alter_student_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
